AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Exclude:
    - 'lib/takagi/middleware/**/*'
    - 'lib/takagi/router.rb'
    - 'lib/takagi/server.rb'
    - 'lib/takagi/server/**/*'
    - 'lib/takagi/logger.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/takagi/server/udp_worker.rb'
    - 'lib/takagi/coap/code_helpers.rb'

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 9
  Exclude:
    - 'lib/takagi/coap/code_helpers.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 140

Naming/AccessorMethodName:
  Enabled: false

Style/ClassVars:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

# Class length is acceptable for core infrastructure classes
Metrics/ClassLength:
  Max: 160

# Allow boolean parameters for DSL methods where the boolean is semantically meaningful
Style/OptionalBooleanParameter:
  Enabled: false

# Allow longer parameter lists for server initialization with many config options
Metrics/ParameterLists:
  Max: 7

# MetadataExtractionContext intentionally doesn't call super - it overrides parent initialization
# Client class doesn't need super - it's a custom wrapper class
Lint/MissingSuper:
  Exclude:
    - 'lib/takagi/router.rb'
    - 'lib/takagi/client.rb'

# Allow multiline block chains for complex transformations
Style/MultilineBlockChain:
  Enabled: false

# CodeHelpers module has complex conversion logic that benefits from clarity over brevity
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/takagi/coap/code_helpers.rb'