AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Exclude:
    - 'lib/takagi/middleware/**/*'
    - 'lib/takagi/router.rb'
    - 'lib/takagi/server.rb'
    - 'lib/takagi/server/**/*'
    - 'lib/takagi/logger.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 140

Naming/AccessorMethodName:
  Enabled: false

Style/ClassVars:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false