module Takagi
  module Middleware
    class Debugging
      # Logs request details before passing it to the next middleware
      # @param request [Takagi::Message::Inbound] Incoming CoAP request
      def call: (untyped request) { (untyped) -> untyped } -> untyped
    end
  end
end
