module Takagi
  module Middleware
    class RateLimiting
      @request_counts: untyped

      @mutex: untyped

      def initialize: () -> void

      def call: (untyped request) { (untyped) -> untyped } -> untyped
    end
  end
end
