module Takagi
  module Message
    # Encodes outbound CoAP request envelopes used when observing remote peers.
    class Request < Base
      @method: untyped

      @uri: untyped

      @token: untyped

      @observe: untyped

      @message_id: untyped

      @payload: untyped

      attr_reader message_id: untyped

      def initialize: (method: untyped, uri: untyped, ?payload: untyped?, ?token: untyped?, **untyped options) -> void

      def to_bytes: () -> untyped

      private

      def encode_options: () -> untyped

      def encode_option: (untyped option_number, untyped value, untyped last_option_number) -> untyped

      def encode_extended: (untyped val) -> untyped
    end
  end
end
